# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-12 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190312_0528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='idss',
        ),
    ]
