# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-15 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_idss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='idss',
        ),
    ]
